### ISSUE TITLE
v11 Proto Checklist

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/PicoBuck#2]
As usual, if any of the issues listed are unavoidable due to size or spacing constraints, please omit the  issue.

(1) No JP prefix on the output through-holes for the screw terminals

(2) Top copper polygons have isolate set to 8 mil instead of 12 mil

(3) jumpers do not have labels in SCH or on BRD

that's it!

**Comment by mhord** [comment]
All fixed, and pushed!
