### ISSUE TITLE
v12 Reds checklist issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/PicoBuck#3]
Two small optional issues:

(1) Looks like the " + OUT - " silk for the middle screw terminal isn't quite centered on the screw terminal. The other two appear to be fine.

(2) In the SCH JP5 and JP6 both have GND nets but both use the common net flag label instead of a GND symbol part. I don't see much of an issue with how the SCH currently looks, but it's in the checklist, so I thought it was worth mentioning.

thanks

**Comment by mhord** [comment]
Did the best I could with recentering the text. That one's hard. Fixed the ground symbols. Thanks Eric!
